# Site settings
title: Plex
email: your-email@domain.com
url: https://jibbsisme.github.io
description: "See links to programs on my computer."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F


# Build settings
markdown: kramdown
permalink: pretty
